# Notebook 01 — Document Loading Tests

## Goal
This notebook tests whether our cybersecurity source documents can be loaded correctly from multiple formats before any cleaning, chunking, or vector indexing.

## File types to test
- PDF
- DOCX
- TXT

## Expected outcome
- Successful loading of all documents
- Basic metadata inspection
- Page-wise validation for PDFs
- Unified document list ready for next-stage preprocessing

# Standard library
from pathlib import Path
from typing import List, Dict
import os

# Data inspection
import pandas as pd

# LangChain document loaders
from langchain_community.document_loaders import PyPDFLoader
from langchain_community.document_loaders import Docx2txtLoader
from langchain_community.document_loaders import TextLoader

print("Imports loaded successfully.")

In [1]:
# Standard library
from pathlib import Path
from typing import List, Dict
import os

# Data inspection
import pandas as pd

# LangChain document loaders
from langchain_community.document_loaders import PyPDFLoader
from langchain_community.document_loaders import Docx2txtLoader
from langchain_community.document_loaders import TextLoader

print("Imports loaded successfully.")

Imports loaded successfully.

In [2]:
# ============================================================
# STEP 1 — Define project paths
# ============================================================

PROJECT_ROOT = Path.cwd().parent
DATA_DIR = PROJECT_ROOT / "data" / "raw"

print("PROJECT_ROOT:", PROJECT_ROOT)
print("DATA_DIR:", DATA_DIR)
print("DATA_DIR exists:", DATA_DIR.exists())

PROJECT_ROOT: d:\Abhishek\Project\LangChain\cybersecurity-multi-doc-rag
DATA_DIR: d:\Abhishek\Project\LangChain\cybersecurity-multi-doc-rag\data\raw
DATA_DIR exists: True

In [3]:
# ============================================================
# STEP 2 — List files present in data/raw
# ============================================================

all_files = sorted([p for p in DATA_DIR.iterdir() if p.is_file()])

print("Files found in data/raw:")
for f in all_files:
    print("-", f.name)

print("\nTotal files found:", len(all_files))

Files found in data/raw:
- audit.txt
- cui-ssp-template-final.docx
- NIST.CSWP.29.pdf
- nist.sp.800-61r2.pdf

Total files found: 4

In [4]:
# ============================================================
# STEP 3 — File type detector
# ============================================================

def detect_file_type(file_path: Path) -> str:
    suffix = file_path.suffix.lower()
    if suffix == ".pdf":
        return "pdf"
    elif suffix == ".docx":
        return "docx"
    elif suffix == ".txt":
        return "txt"
    else:
        return "unsupported"

In [5]:
# ============================================================
# STEP 4 — Generic loader function
# ============================================================

def load_single_document(file_path: Path):
    """
    Load one file using the appropriate LangChain loader.
    Returns a list of LangChain Document objects.
    """
    file_type = detect_file_type(file_path)

    if file_type == "pdf":
        loader = PyPDFLoader(str(file_path))
        docs = loader.load()

    elif file_type == "docx":
        loader = Docx2txtLoader(str(file_path))
        docs = loader.load()

    elif file_type == "txt":
        loader = TextLoader(str(file_path), encoding="utf-8")
        docs = loader.load()

    else:
        raise ValueError(f"Unsupported file type: {file_path.suffix}")

    return docs

In [6]:
# ============================================================
# STEP 5 — Load all supported documents
# ============================================================

loaded_documents = []
loading_summary = []

for file_path in all_files:
    file_type = detect_file_type(file_path)

    if file_type == "unsupported":
        print(f"Skipping unsupported file: {file_path.name}")
        continue

    try:
        docs = load_single_document(file_path)
        loaded_documents.extend(docs)

        loading_summary.append({
            "file_name": file_path.name,
            "file_type": file_type,
            "num_langchain_docs": len(docs),
            "status": "success"
        })

        print(f"Loaded successfully: {file_path.name} | type={file_type} | docs={len(docs)}")

    except Exception as e:
        loading_summary.append({
            "file_name": file_path.name,
            "file_type": file_type,
            "num_langchain_docs": 0,
            "status": f"failed: {str(e)}"
        })

        print(f"Failed to load: {file_path.name}")
        print("Error:", e)

print("\nTotal loaded LangChain document objects:", len(loaded_documents))

Loaded successfully: audit.txt | type=txt | docs=1
Loaded successfully: cui-ssp-template-final.docx | type=docx | docs=1
Loaded successfully: NIST.CSWP.29.pdf | type=pdf | docs=32
Loaded successfully: nist.sp.800-61r2.pdf | type=pdf | docs=80

Total loaded LangChain document objects: 114

In [7]:
# ============================================================
# STEP 6 — Show loading summary
# ============================================================

summary_df = pd.DataFrame(loading_summary)
display(summary_df)

                     file_name file_type  num_langchain_docs   status
0                    audit.txt       txt                   1  success
1  cui-ssp-template-final.docx      docx                   1  success
2             NIST.CSWP.29.pdf       pdf                  32  success
3         nist.sp.800-61r2.pdf       pdf                  80  success

In [8]:
# ============================================================
# STEP 7 — Inspect metadata and text sample from each file
# ============================================================

for row in loading_summary:
    if row["status"] != "success":
        continue

    file_name = row["file_name"]
    matched_docs = [
        doc for doc in loaded_documents
        if Path(doc.metadata.get("source", "")).name == file_name
    ]

    print("=" * 100)
    print("FILE:", file_name)
    print("TYPE:", row["file_type"])
    print("NUMBER OF DOC OBJECTS:", len(matched_docs))

    if matched_docs:
        first_doc = matched_docs[0]
        print("METADATA:", first_doc.metadata)
        print("\nTEXT PREVIEW:\n")
        print(first_doc.page_content[:1200])
        print("\n")

====================================================================================================
FILE: audit.txt
TYPE: txt
NUMBER OF DOC OBJECTS: 1
METADATA: {'source': 'd:\\Abhishek\\Project\\LangChain\\cybersecurity-multi-doc-rag\\data\\raw\\audit.txt'}

TEXT PREVIEW:

AUDIT TRAILS

Audit trails maintain a record of system activity both by system and
application processes and by user activity of systems and applications.  In
conjunction with appropriate tools and procedures, audit trails can assist
in detecting security violations, performance problems, and flaws in
applications.  This bulletin focuses on audit trails as a technical control
and discusses the benefits and objectives of audit trails, the types of
audit trails, and some common implementation issues.

An audit trail is a series of records of computer events, about an
operating system, an application, or user activities.  A computer system
may have several audit trails, each devoted to a particular type of
activity.  Auditing is a review and analysis of management, operational,
and technical controls.  The auditor can obtain valuable information about
activity on a computer system from the audit trail.  Audit trails improve
the auditability of the computer system.

Audit trails may be used as either a support for regular system operations
or a kind of insurance policy or as both of these.  As insurance, audit
trails are maintained but are not used unless needed, such as after a
syste


====================================================================================================
FILE: cui-ssp-template-final.docx
TYPE: docx
NUMBER OF DOC OBJECTS: 1
METADATA: {'source': 'd:\\Abhishek\\Project\\LangChain\\cybersecurity-multi-doc-rag\\data\\raw\\cui-ssp-template-final.docx'}

TEXT PREVIEW:

<<Insert name>> SYSTEM SECURITY PLAN   	                    Last Updated:  <<Insert date>>

		SYSTEM IDENTIFICATION



		System Name/Title: [State the name of the system.  Spell out acronyms.]



System Categorization:  Moderate Impact for Confidentiality



System Unique Identifier: [Insert the System Unique Identifier]



		Responsible Organization:



Name:



Address:



Phone:





Information Owner (Government point of contact responsible for providing and/or receiving CUI):

Name:



Title:



Office Address:



Work Phone:



e-Mail Address:





 System Owner (assignment of security responsibility):



Name:



Title:



Office Address:



Work Phone:



e-Mail Address:





 System Security Officer:



Name:



Title:



Office Address:



Work Phone:



e-Mail Address:



		General Description/Purpose of System:  What is the function/purpose of the system?  [Provide a short, high-level description of the function/purpose of the system.]



Number of end users and privileged users: [In the table below, provide the approximate number of users and administrators of the system.  Include all those with privileged access such as system administrators, data


====================================================================================================
FILE: NIST.CSWP.29.pdf
TYPE: pdf
NUMBER OF DOC OBJECTS: 32
METADATA: {'producer': 'Adobe PDF Library 23.8.53', 'creator': 'Acrobat PDFMaker 23 for Word', 'creationdate': '2024-03-06T15:46:45-05:00', 'author': 'National Institute of Standards and Technology', 'category': '', 'comments': '', 'company': '', 'contenttypeid': '0x01010039BCE524E722AC4882B40135ECFFCA17', 'doi (machine-readable pubid)': 'NIST.CSWP.29', 'doi value': 'NIST.CSWP.29', 'grammarlydocumentid': 'b30b891388ea4e76087a9e77cdc664db0d1859c0ea00bed42f0042bade33dbcd', 'keywords': 'cybersecurity; Cybersecurity Framework (CSF); cybersecurity risk governance; cybersecurity risk management; enterprise risk management; Profiles; Tiers', 'manager': '', 'mediaserviceimagetags': '', 'moddate': '2025-06-04T10:58:23-04:00', 'pubid': 'NIST CSWP 29', 'pubid (doi)': 'NIST.CSWP.29', 'pubid (human-readable)': 'NIST CSWP 29', 'publication date': 'Month DD, 2024', 'shorttitleline1': 'The NIST Cybersecurity Framework (CSF) 2.0', 'shorttitleline2': '', 'sourcemodified': '', 'subject': 'The NIST Cybersecurity Framework (CSF) 2.0 provides guidance to industry, government agencies, and other organizations to manage cybersecurity risks. It offers a taxonomy of high-level cybersecurity outcomes that can be used by any organization — regardless of its size, sector, or maturity — to better understand, assess, prioritize, and communicate its cybersecurity efforts. The CSF does not prescribe how outcomes should be achieved. Rather, it links to online resources that provide additional guidance on practices and controls that could be used to achieve those outcomes. This document describes CSF 2.0, its components, and some of the many ways that it can be used.', 'title': 'The NIST Cybersecurity Framework (CSF) 2.0', 'source': 'd:\\Abhishek\\Project\\LangChain\\cybersecurity-multi-doc-rag\\data\\raw\\NIST.CSWP.29.pdf', 'total_pages': 32, 'page': 0, 'page_label': '1'}

TEXT PREVIEW:

National Institute of Standards and Technology
This publication is available free of charge from: https://doi.org/10.6028/NIST.CSWP.29
February 26, 2024
The NIST Cybersecurity
Framework (CSF) 2.0


====================================================================================================
FILE: nist.sp.800-61r2.pdf
TYPE: pdf
NUMBER OF DOC OBJECTS: 80
METADATA: {'producer': 'Microsoft® Word 2010', 'creator': 'Microsoft® Word 2010', 'creationdate': '2012-08-06T10:11:18-04:00', 'author': 'Cichonski, Paul R. ; Millar, Thomas; Scarfone, Karen A.; Grance, Timothy', 'keywords': 'NIST SP 800-61 Revision 2, Computer Security Incident Handling Guide, computer security incident; incident handling; incident response; information security', 'moddate': '2025-04-03T08:35:10-04:00', 'subject': 'Computer security incident response has become an important component of information technology (IT) programs. Because performing incident response effectively is a complex undertaking, establishing a successful incident response capability requires substantial planning and resources. This publication assists organizations in establishing computer security incident response capabilities and handling incidents efficiently and effectively. This publication provides guidelines for incident handling, particularly for analyzing incident-related data and determining the appropriate response to each incident. The guidelines can be followed independently of particular hardware platforms, operating systems, protocols, or applications.', 'title': 'Computer Security Incident Handling Guide', 'source': 'd:\\Abhishek\\Project\\LangChain\\cybersecurity-multi-doc-rag\\data\\raw\\nist.sp.800-61r2.pdf', 'total_pages': 80, 'page': 0, 'page_label': '1'}

TEXT PREVIEW:

Date updated: April 3, 2025
Withdrawn NIST Technical Series Publication


Warning Notice

The attached publication has been withdrawn (archived), and is provided solely for historical purposes.
It may have been superseded by another publication (indicated below).

Withdrawn Publication
Series/Number NIST Special Publication (SP) 800-61 Revision 2
Title Computer Security Incident Handling Guide
Publication Date(s) August 2012
Withdrawal Date April 3, 2025
Withdrawal Note NIST SP 800-61 Rev. 2 is withdrawn and superseded in its entirety by NIST SP
800-61r3 (Revision 3)
Superseding Publication(s) (if applicable)
The attached publication has been superseded by the following publication(s):
Series/Number NIST SP 800-61r3
Title Incident Response Recommendations and Considerations for Cybersecurity
Risk Management: A CSF 2.0 Community Profile
Author(s) A. Nelson; S. Rekhi; M. Souppaya; K. Scarfone
Publication Date(s) April 3, 2025
URL/DOI https://doi.org/10.6028/NIST.SP.800-61r3
Additional Information (if applicable)
Contact Computer Security Division (Information Technology Laboratory)
Latest revision of the
attached publication

Related Information https:/

In [9]:
# ============================================================
# STEP 8 — PDF page-level inspection
# ============================================================

pdf_docs = [
    doc for doc in loaded_documents
    if str(doc.metadata.get("source", "")).lower().endswith(".pdf")
]

print("Total PDF page documents:", len(pdf_docs))

for i, doc in enumerate(pdf_docs[:5]):
    print("=" * 100)
    print(f"PDF SAMPLE #{i+1}")
    print("SOURCE:", doc.metadata.get("source"))
    print("PAGE:", doc.metadata.get("page"))
    print("TEXT PREVIEW:\n")
    print(doc.page_content[:1000])
    print("\n")

Total PDF page documents: 112
====================================================================================================
PDF SAMPLE #1
SOURCE: d:\Abhishek\Project\LangChain\cybersecurity-multi-doc-rag\data\raw\NIST.CSWP.29.pdf
PAGE: 0
TEXT PREVIEW:

National Institute of Standards and Technology
This publication is available free of charge from: https://doi.org/10.6028/NIST.CSWP.29
February 26, 2024
The NIST Cybersecurity
Framework (CSF) 2.0


====================================================================================================
PDF SAMPLE #2
SOURCE: d:\Abhishek\Project\LangChain\cybersecurity-multi-doc-rag\data\raw\NIST.CSWP.29.pdf
PAGE: 1
TEXT PREVIEW:

T he NIST Cybersecurity Framework (CSF) 2.0
 i
NIST CSWP 29
February 26, 2024
Abstract
T
he NIST Cybersecurity Framework (CSF) 2.0 provides guidance to industry, government
agencies, and other organizations to manage cybersecurity risks. It offers a taxonomy of high-
level cybersecurity outcomes that can be used by any organization — regardless of its size,
sector, or maturity — to better understand, assess, prioritize, and communicate its
cybersecurity efforts. The CSF does not prescribe how outcomes should be achieved. Rather, it
links to online resources that provide additional guidance on practices and controls that could
be used to achieve those outcomes. This document describes CSF 2.0, its components, and
some of the many ways that it can be used.
Keywords
cybersecurity; Cybersecurity Framework (CSF); cybersecurity risk governance; cybersecurity risk
management; enterprise risk management; Profiles; Tiers.
Audience
Individuals responsible for developing and leadi


====================================================================================================
PDF SAMPLE #3
SOURCE: d:\Abhishek\Project\LangChain\cybersecurity-multi-doc-rag\data\raw\NIST.CSWP.29.pdf
PAGE: 2
TEXT PREVIEW:

NIST CSWP 29  The NIST Cybersecurity Framework (CSF) 2.0
February 26, 2024
 ii
Acknowledgments
The CSF is the result of a multi-year collaborative effort across industry, academia, and
government in the United States and around the world. NIST acknowledges and thanks all of
those who have contributed to this revised CSF. Information on the CSF development process
can be found on the NIST CSF website. Lessons learned about th e use of the CSF can always be
shared with NIST at cyberframework@nist.gov.


====================================================================================================
PDF SAMPLE #4
SOURCE: d:\Abhishek\Project\LangChain\cybersecurity-multi-doc-rag\data\raw\NIST.CSWP.29.pdf
PAGE: 3
TEXT PREVIEW:

NIST CSWP 29  The NIST Cybersecurity Framework (CSF) 2.0
February 26, 2024
 iii
Table of Contents
1. Cybersecurity Framework (CSF) Overview .......................................................................................1
2. Introduction to the CSF Core ...........................................................................................................3
3. Introduction to CSF Profiles and Tiers .............................................................................................6
4. Introduction to Online Resources That Supplement the CSF ............................................................9
5. Improving Cybersecurity Risk Communication and Integration ...................................................... 10
Appendix A. CSF Core ....................................................................................................................... 15
Appendix B. CSF Tiers .......................................................................


====================================================================================================
PDF SAMPLE #5
SOURCE: d:\Abhishek\Project\LangChain\cybersecurity-multi-doc-rag\data\raw\NIST.CSWP.29.pdf
PAGE: 4
TEXT PREVIEW:

NIST CSWP 29  The NIST Cybersecurity Framework (CSF) 2.0
February 26, 2024
 iv
Preface
T
he Cybersecurity Framework (CSF) 2.0 is designed to help organizations of all sizes and sectors
— including industry, government, academia, and nonprofit — to manage and reduce their
cybersecurity risks. It is useful regardless of the maturity level and technical sophistication of an
organization’s cybersecurity programs. Nevertheless, the CSF does not embrace a one-size-fits-
all approach. Each organization has both common and unique risks, as well as varying risk
appetites and tolerances, specific missions, and objectives to achieve those missions. By
necessity, the way organizations implement the CSF will vary.
Ideally, the CSF will be used to address cybersecurity risks alongside other risks of the
enterprise, including those that are financial, privacy, supply chain, reputational, technological,
or physical in nature.
The CSF describes desired outcomes that are intended to be unde

In [10]:
# ============================================================
# STEP 9 — DOCX and TXT inspection
# ============================================================

non_pdf_docs = [
    doc for doc in loaded_documents
    if not str(doc.metadata.get("source", "")).lower().endswith(".pdf")
]

print("Total DOCX/TXT documents:", len(non_pdf_docs))

for i, doc in enumerate(non_pdf_docs[:5]):
    print("=" * 100)
    print(f"NON-PDF SAMPLE #{i+1}")
    print("SOURCE:", doc.metadata.get("source"))
    print("METADATA:", doc.metadata)
    print("TEXT PREVIEW:\n")
    print(doc.page_content[:1000])
    print("\n")

Total DOCX/TXT documents: 2
====================================================================================================
NON-PDF SAMPLE #1
SOURCE: d:\Abhishek\Project\LangChain\cybersecurity-multi-doc-rag\data\raw\audit.txt
METADATA: {'source': 'd:\\Abhishek\\Project\\LangChain\\cybersecurity-multi-doc-rag\\data\\raw\\audit.txt'}
TEXT PREVIEW:

AUDIT TRAILS

Audit trails maintain a record of system activity both by system and
application processes and by user activity of systems and applications.  In
conjunction with appropriate tools and procedures, audit trails can assist
in detecting security violations, performance problems, and flaws in
applications.  This bulletin focuses on audit trails as a technical control
and discusses the benefits and objectives of audit trails, the types of
audit trails, and some common implementation issues.

An audit trail is a series of records of computer events, about an
operating system, an application, or user activities.  A computer system
may have several audit trails, each devoted to a particular type of
activity.  Auditing is a review and analysis of management, operational,
and technical controls.  The auditor can obtain valuable information about
activity on a computer system from the audit trail.  Audit trails improve
the auditability of the computer system.

Audit trails may be us


====================================================================================================
NON-PDF SAMPLE #2
SOURCE: d:\Abhishek\Project\LangChain\cybersecurity-multi-doc-rag\data\raw\cui-ssp-template-final.docx
METADATA: {'source': 'd:\\Abhishek\\Project\\LangChain\\cybersecurity-multi-doc-rag\\data\\raw\\cui-ssp-template-final.docx'}
TEXT PREVIEW:

<<Insert name>> SYSTEM SECURITY PLAN   	                    Last Updated:  <<Insert date>>

		SYSTEM IDENTIFICATION



		System Name/Title: [State the name of the system.  Spell out acronyms.]



System Categorization:  Moderate Impact for Confidentiality



System Unique Identifier: [Insert the System Unique Identifier]



		Responsible Organization:



Name:



Address:



Phone:





Information Owner (Government point of contact responsible for providing and/or receiving CUI):

Name:



Title:



Office Address:



Work Phone:



e-Mail Address:





 System Owner (assignment of security responsibility):



Name:



Title:



Office Address:



Work Phone:



e-Mail Address:





 System Security Officer:



Name:



Title:



Office Address:



Work Phone:



e-Mail Address:



		General Description/Purpose of System:  What is the function/purpose of the system?  [Provide a short, high-level description of the function/purpose of the system.]



Number of end

In [11]:
# ============================================================
# STEP 10 — Basic statistics
# ============================================================

stats_rows = []

for doc in loaded_documents:
    source = doc.metadata.get("source", "unknown")
    file_name = Path(source).name if source != "unknown" else "unknown"
    file_type = Path(source).suffix.lower().replace(".", "") if source != "unknown" else "unknown"
    char_count = len(doc.page_content)
    word_count = len(doc.page_content.split())

    stats_rows.append({
        "file_name": file_name,
        "file_type": file_type,
        "page": doc.metadata.get("page", None),
        "char_count": char_count,
        "word_count": word_count
    })

stats_df = pd.DataFrame(stats_rows)
display(stats_df.head(20))

print("\nGrouped summary:")
display(
    stats_df.groupby(["file_name", "file_type"], dropna=False)
    .agg(
        num_docs=("file_name", "count"),
        total_chars=("char_count", "sum"),
        total_words=("word_count", "sum"),
        avg_chars=("char_count", "mean")
    )
    .reset_index()
)

                      file_name file_type  page  char_count  word_count
0                     audit.txt       txt   NaN       20319        3105
1   cui-ssp-template-final.docx      docx   NaN       35629        4039
2              NIST.CSWP.29.pdf       pdf   0.0         200          24
3              NIST.CSWP.29.pdf       pdf   1.0        2284         316
4              NIST.CSWP.29.pdf       pdf   2.0         512          82
5              NIST.CSWP.29.pdf       pdf   3.0        2016         131
6              NIST.CSWP.29.pdf       pdf   4.0        3406         504
7              NIST.CSWP.29.pdf       pdf   5.0        2788         401
8              NIST.CSWP.29.pdf       pdf   6.0        2350         340
9              NIST.CSWP.29.pdf       pdf   7.0        2106         295
10             NIST.CSWP.29.pdf       pdf   8.0        3024         422
11             NIST.CSWP.29.pdf       pdf   9.0        1432         199
12             NIST.CSWP.29.pdf       pdf  10.0        1997         289
13             NIST.CSWP.29.pdf       pdf  11.0        3156         458
14             NIST.CSWP.29.pdf       pdf  12.0        1108         156
15             NIST.CSWP.29.pdf       pdf  13.0        2694         387
16             NIST.CSWP.29.pdf       pdf  14.0        2161         306
17             NIST.CSWP.29.pdf       pdf  15.0        3589         485
18             NIST.CSWP.29.pdf       pdf  16.0        2621         362
19             NIST.CSWP.29.pdf       pdf  17.0        2522         343

Grouped summary:

,file_name,file_type,num_docs,total_chars,total_words,avg_chars
0,NIST.CSWP.29.pdf,pdf,32,69590,9468,2174.6875
1,audit.txt,txt,1,20319,3105,20319.0000
2,cui-ssp-template-final.docx,docx,1,35629,4039,35629.0000
3,nist.sp.800-61r2.pdf,pdf,80,231248,31965,2890.6000

In [12]:
# ============================================================
# STEP 11 — Standardize metadata schema
# ============================================================

standardized_documents = []

for idx, doc in enumerate(loaded_documents):
    source_path = doc.metadata.get("source", "")
    source_path = str(source_path)

    file_path = Path(source_path) if source_path else None
    file_name = file_path.name if file_path else "unknown"
    doc_type = file_path.suffix.lower().replace(".", "") if file_path else "unknown"

    standardized_metadata = {
        "document_id": f"doc_{idx:04d}",
        "file_name": file_name,
        "source_path": source_path,
        "doc_type": doc_type,
        "page_number": doc.metadata.get("page", None),
        "loader_metadata": doc.metadata
    }

    doc.metadata = standardized_metadata
    standardized_documents.append(doc)

print("Standardized documents created:", len(standardized_documents))
print("\nSample standardized metadata:")
print(standardized_documents[0].metadata if standardized_documents else "No documents loaded")

Standardized documents created: 114

Sample standardized metadata:
{'document_id': 'doc_0000', 'file_name': 'audit.txt', 'source_path': 'd:\\Abhishek\\Project\\LangChain\\cybersecurity-multi-doc-rag\\data\\raw\\audit.txt', 'doc_type': 'txt', 'page_number': None, 'loader_metadata': {'source': 'd:\\Abhishek\\Project\\LangChain\\cybersecurity-multi-doc-rag\\data\\raw\\audit.txt'}}

In [13]:
# ============================================================
# STEP 12 — Final standardized inspection
# ============================================================

preview_rows = []

for doc in standardized_documents[:15]:
    preview_rows.append({
        "document_id": doc.metadata.get("document_id"),
        "file_name": doc.metadata.get("file_name"),
        "doc_type": doc.metadata.get("doc_type"),
        "page_number": doc.metadata.get("page_number"),
        "source_path": doc.metadata.get("source_path"),
        "text_preview": doc.page_content[:200].replace("\n", " ")
    })

preview_df = pd.DataFrame(preview_rows)
display(preview_df)

,document_id,file_name,doc_type,page_number,source_path,text_preview
0,doc_0000,audit.txt,txt,NaN,d:\Abhishek\Project\LangChain\cybersecurity-mu...,AUDIT TRAILS Audit trails maintain a record o...
1,doc_0001,cui-ssp-template-final.docx,docx,NaN,d:\Abhishek\Project\LangChain\cybersecurity-mu...,<<Insert name>> SYSTEM SECURITY PLAN \t ...
2,doc_0002,NIST.CSWP.29.pdf,pdf,0.0,d:\Abhishek\Project\LangChain\cybersecurity-mu...,National Institute of Standards and Technology...
3,doc_0003,NIST.CSWP.29.pdf,pdf,1.0,d:\Abhishek\Project\LangChain\cybersecurity-mu...,T he NIST Cybersecurity Framework (CSF) 2.0 ...
4,doc_0004,NIST.CSWP.29.pdf,pdf,2.0,d:\Abhishek\Project\LangChain\cybersecurity-mu...,NIST CSWP 29 The NIST Cybersecurity Framework...
5,doc_0005,NIST.CSWP.29.pdf,pdf,3.0,d:\Abhishek\Project\LangChain\cybersecurity-mu...,NIST CSWP 29 The NIST Cybersecurity Framework...
6,doc_0006,NIST.CSWP.29.pdf,pdf,4.0,d:\Abhishek\Project\LangChain\cybersecurity-mu...,NIST CSWP 29 The NIST Cybersecurity Framework...
7,doc_0007,NIST.CSWP.29.pdf,pdf,5.0,d:\Abhishek\Project\LangChain\cybersecurity-mu...,NIST CSWP 29 The NIST Cybersecurity Framework...
8,doc_0008,NIST.CSWP.29.pdf,pdf,6.0,d:\Abhishek\Project\LangChain\cybersecurity-mu...,NIST CSWP 29 The NIST Cybersecurity Framework...
9,doc_0009,NIST.CSWP.29.pdf,pdf,7.0,d:\Abhishek\Project\LangChain\cybersecurity-mu...,NIST CSWP 29 The NIST Cybersecurity Framework...
10,doc_0010,NIST.CSWP.29.pdf,pdf,8.0,d:\Abhishek\Project\LangChain\cybersecurity-mu...,NIST CSWP 29 The NIST Cybersecurity Framework...
11,doc_0011,NIST.CSWP.29.pdf,pdf,9.0,d:\Abhishek\Project\LangChain\cybersecurity-mu...,NIST CSWP 29 The NIST Cybersecurity Framework...
12,doc_0012,NIST.CSWP.29.pdf,pdf,10.0,d:\Abhishek\Project\LangChain\cybersecurity-mu...,NIST CSWP 29 The NIST Cybersecurity Framework...
13,doc_0013,NIST.CSWP.29.pdf,pdf,11.0,d:\Abhishek\Project\LangChain\cybersecurity-mu...,NIST CSWP 29 The NIST Cybersecurity Framework...
14,doc_0014,NIST.CSWP.29.pdf,pdf,12.0,d:\Abhishek\Project\LangChain\cybersecurity-mu...,NIST CSWP 29 The NIST Cybersecurity Framework...

In [14]:
# ============================================================
# STEP 13 — Save loading report for later notebooks
# ============================================================

OUTPUT_DIR = PROJECT_ROOT / "data" / "interim" / "extracted_docs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

loading_report_path = OUTPUT_DIR / "document_loading_summary.csv"
preview_report_path = OUTPUT_DIR / "document_loading_preview.csv"

summary_df.to_csv(loading_report_path, index=False)
preview_df.to_csv(preview_report_path, index=False)

print("Saved:", loading_report_path)
print("Saved:", preview_report_path)

Saved: d:\Abhishek\Project\LangChain\cybersecurity-multi-doc-rag\data\interim\extracted_docs\document_loading_summary.csv
Saved: d:\Abhishek\Project\LangChain\cybersecurity-multi-doc-rag\data\interim\extracted_docs\document_loading_preview.csv

In [15]:
# ============================================================
# STEP 14 — Final conclusion
# ============================================================

print("Notebook 01 completed.")
print(f"Total supported source files found: {len([f for f in all_files if detect_file_type(f) != 'unsupported'])}")
print(f"Total loaded document objects: {len(standardized_documents)}")

successful_files = summary_df[summary_df["status"] == "success"]["file_name"].tolist()
failed_files = summary_df[summary_df["status"] != "success"]["file_name"].tolist()

print("\nSuccessful files:")
for f in successful_files:
    print("-", f)

print("\nFailed files:")
if failed_files:
    for f in failed_files:
        print("-", f)
else:
    print("None")

Notebook 01 completed.
Total supported source files found: 4
Total loaded document objects: 114

Successful files:
- audit.txt
- cui-ssp-template-final.docx
- NIST.CSWP.29.pdf
- nist.sp.800-61r2.pdf

Failed files:
None